Intro and File Pages
talha-ashraf-brainx/Document-Scanner-pdf-Swift pull request #1
Opened 2023-06-20 11:46 UTC by talha-ashraf-brainx

2023-06-23 11:27 UTC, arslan-basit-brainx requested changes

2023-07-10 12:20 UTC, abdur-rehman-brainx requested changes

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/AppDocumentDirectory.swift
> +        if let documentDirectory = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first {
use guard let instead of If let

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/AppDocumentDirectory.swift
> +            print("App folder already exists.")
Remove extra code like Print statements and unwanted comments

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/BaseViews/BaseUIView.swift
> +            fatalError("Could not load BasicTaskTile from nib")
use string literals as localized strings or local variables

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/Components/BottomNavigationBar/BottomNavigationBar.swift
> +
Add pragma  MARKs for outlets, private methods, initializer methods, etc

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/Extentions/UIViewController.swift
> +    static var storyboardId: String {
there should be line consistence

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/Extentions/UIViewController.swift
> +extension UIStoryboard {
UI components extensions should be in new File

2023-07-10 12:20 UTC, abdur-rehman-brainx commented on Document Scanner pdf/Screens/Intro/IntroViewController.swift
> +    let subTitles: [String] = ["typesetting industry. Lorem Ipsum has been industry's standard dummy text since the 1500s.", "typesetting industry. Lorem Ipsum has been industry's standard dummy text
as Above

2023-09-26 18:50 UTC, merged